name: Build x86 Linux Binary

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libpcap-dev

      - name: Download dependencies
        run: go mod tidy

      - name: Download dependencies2
        run: go mod download

      - name: Build binary for linux/amd64
        run: |
          GOOS=linux GOARCH=amd64 go build -v -o flowstats_linux_amd64 .

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-binary
          path: flowstats_linux_amd64
